### About

This is the notebook for preparing data for a model to predict wining side by player performance, namely KDA and minion killed.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('cleanData.csv', nrows=20)

In [4]:
df.head(5)

,Unnamed: 0,id,matchid,player,championid,team_role,ss1,ss2,item1,item2,...,totminionskilled,pinksbought,wardsplaced,duration,baronkills,heraldkills,dragonkills,firsttower,firstinhib,firstblood
0,0,9,10,1,19,1 - JUNGLE,4,11,3748.0,2003.0,...,42.0,0.0,10.0,1909.0,0,0,0,1,0,0.0
1,1,10,10,2,267,1 - DUO_SUPPORT,3,4,2301.0,3111.0,...,17.0,1.0,17.0,1909.0,0,0,0,1,0,0.0
2,2,11,10,3,119,1 - DUO_CARRY,7,4,1055.0,3072.0,...,205.0,1.0,13.0,1909.0,0,0,0,1,0,0.0
3,3,12,10,4,114,1 - TOP,12,4,1029.0,3078.0,...,164.0,0.0,3.0,1909.0,0,0,0,1,0,0.0
4,4,13,10,5,112,1 - MID,4,3,3020.0,1058.0,...,235.0,0.0,10.0,1909.0,0,0,0,1,0,0.0

In [4]:
#creating columns name
team1champions = [0] * (championsNumber)
for i in range(len(team1champions)):
    team1champions[i] = "t1_"+str(champions[i])  
team2champions = [0] * (championsNumber)
for i in range(len(team2champions)):
    team2champions[i] = "t2_"+str(champions[i])  
resultantCols = team1champions
resultantCols.extend(team2champions)
resultantCols.append('team1Win')
len(resultantCols)

273

In [5]:
rows_list = []
tempRow = [0] * (2*championsNumber)
for idx, x in df['championid'].iteritems():
    
    if((idx+1)%10!=0 and (idx+1)%10<6):#team1 selection
        i = champions.index(x)
        tempRow[i] = 1.0
    else:#team2 selection
        i = champions.index(x)
        tempRow[2*i+1] = 1.0
    
    
    #new match, reset the tempRow    
    if((idx+1)%10==0):         
        winOrNot = df.get_value(idx, 'win')
        if(winOrNot==1):   #ie team 2 win
            winOrNot = -1.0 #ie team 1 lose
        else:
            winOrNot = 1.0
        
        tempRow.append(winOrNot)
        
        #we need champions with two times
        tempD = dict(zip(resultantCols ,tempRow))
        rows_list.append(tempD)
        tempRow = [0] * (2*championsNumber)

In [6]:
heroSelect = pd.DataFrame(rows_list)

#sorting team1 heros after team2 and team1Win as the first column
heroSelect.reindex_axis(sorted(heroSelect.columns), axis=1)
cols = heroSelect.columns.tolist()
cols.insert(0, cols.pop(cols.index('team1Win')))
heroSelect = heroSelect.reindex(columns=cols)

In [7]:
heroSelect.to_csv('heroSelect.csv')
heroSelect.head(20)

,team1Win,t1_1,t1_10,t1_101,t1_102,t1_103,t1_104,t1_105,t1_106,t1_107,...,t2_85,t2_86,t2_89,t2_9,t2_90,t2_91,t2_92,t2_96,t2_98,t2_99
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
1,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
2,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
3,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
4,-1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
5,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
6,-1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
7,-1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
8,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
9,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
10,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
11,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
12,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
13,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
14,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
15,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
16,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
17,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
18,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0
19,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0,0